// <auto-generated />
using System;
using Api.Comum.Repositorios;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220529163539_IniciandoBanco")]
    partial class IniciandoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api.Dominio.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhSaida")
                        .HasColumnType("bit");

                    b.Property<int>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("Api.Dominio.Usuarios.Salario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataRecorrencia")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NaoPossuiData")
                        .HasColumnType("bit");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Salarios");
                });

            modelBuilder.Entity("Api.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Api.Dominio.Lancamento", b =>
                {
                    b.HasOne("Api.Dominio.Usuarios.Usuario", null)
                        .WithMany("Lancamentos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("Api.Dominio.Usuarios.Usuario", b =>
                {
                    b.HasOne("Api.Dominio.Usuarios.Salario", "Salario")
                        .WithMany()
                        .HasForeignKey("SalarioId");

                    b.Navigation("Salario");
                });

            modelBuilder.Entity("Api.Dominio.Usuarios.Usuario", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
